image:
  file: .gitpod.Dockerfile

tasks:
  - command: run-jupyter


#
# manual option
#

# tasks:
#   - command: |
#        jupyter notebook --NotebookApp.token='' --NotebookApp.allow_origin="$(gp url 8888)" --NotebookApp.allow_remote_access=True --NotebookApp.use_redirect_file=False --no-browser

# ports:
#   - port: 8888
#     onOpen: open-browser
